language: python
if: tag IS blank
jobs:
  include:
    - name: "On Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH; OUTPUT=corona-windows.exe; TAG=$(git log --format=%h -1)
    - name: "On macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      python: 3.5
      before_install:
        - pip3 install virtualenv
        - virtualenv env
        - source env/bin/activate
      env:
        - OUTPUT=corona-macos
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install setuptools
  - pip3 install pyinstaller
# command to run tests
script:
  - pyinstaller corona.py --onefile -n $OUTPUT
  - ls -l dist
before_deploy:
  - export RELEASE_TITLE="#$TRAVIS_BUILD_NUMBER"
  - export TRAVIS_TAG=$RELEASE_TITLE
deploy:
  name: $RELEASE_TITLE
  provider: releases
  api_key:
    secure: QhGNgW2vipq3jR5IiGiW26xNNyX9PtrNlmSm8a4+vrOBd/eZDy6XfzzTp8CFXjy82xcBwH2jAphJvGaR3ahcnBqYgst9rU+N8r8PwBImhIAlP5EKxtrcUjknD00DXN9rvWG+pYQUtcss5GJiCtO10MAd8SVvYjjUnV5R6uRUddP+HuJTHqqNmjQ0B2/kvaRP+mVSW1J2UOEtsCsPTHohS+/B//rDakHB7M5+pEHJRQKME+0tDVaG+RTd9GZsHEvUGKfQ5OjjzpjY378id+m4lElLqTfykecyTi95eoWa/rrP3iTcU5erotdjSGojQAtQwihv1bSCKo2VHV9ktoZNmmOzDq50Odc9FvzGA2VksHfgS9kjKnDjGiUNL092FWyvqie/gav99CLSV4YDBlC2IaznHA+PcHl6bMLB0UP1Zac2Di884r8hXYfi41mKXnf9/lwZBdL6U5AF/8KloBh+XYGrlD4Uc21KjidIvaN42r7cHebSQ+1Gs5T9+p6QoGMw9AV8XYQfDlH6ArZF4D/iFJPmPpMTidIYlnLsQvAPbQcF9JGYmaB96Dhf70+Pm9kq8F1mHvfszkXZFh7Sx3QSlrrbxORe+N5QzLlW/yjaJ11kkzWjshwIp/9odtmCnTGugKoeQreSUYOFDKtkNukra11sHZeeYI/5VZEHaI8RLzg=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: andrewcell/Corona
    #tags: true
    branch: master